"""
LangGraph supervisor graph for the Nivesh multi-agent system.

build_graph(memory_context):
    Assembles and compiles the full StateGraph:
      START → supervisor → [stock_agent | fund_agent | portfolio_agent] → supervisor → END

    The supervisor uses ChatGroq with structured output (RouteDecision) to decide
    which specialist agent to invoke, or FINISH when the answer is ready.

    Each worker agent runs as a sub-graph (create_react_agent). New messages
    generated by workers are appended to the shared state; the supervisor sees
    them on the next turn and decides FINISH.
"""

import logging
from typing import Annotated, Literal, Optional

from langchain_core.messages import BaseMessage, SystemMessage
from langchain_groq import ChatGroq
from langgraph.graph import END, START, StateGraph
from langgraph.graph.message import add_messages
from pydantic import BaseModel
from typing_extensions import TypedDict

from ..config import settings
from .agents import build_fund_agent, build_portfolio_agent, build_stock_agent

logger = logging.getLogger(__name__)


# ── State ──────────────────────────────────────────────────────────────────────

class AgentState(TypedDict):
    messages: Annotated[list[BaseMessage], add_messages]
    next: Optional[str]


# ── Routing schema ─────────────────────────────────────────────────────────────

class RouteDecision(BaseModel):
    next: Literal["stock_agent", "fund_agent", "portfolio_agent", "FINISH"]
    reason: str


# ── System prompts ─────────────────────────────────────────────────────────────

SUPERVISOR_SYSTEM = """\
You are a routing supervisor for Nivesh, an Indian equity market research platform.
Your ONLY job is to decide which specialist agent should handle the user's query,
then return FINISH once the specialist has provided a complete answer.

Available agents:
- stock_agent: NSE/BSE stock prices, technical indicators (RSI, MACD, EMAs),
  fundamentals (PE, PB, ROE, ROCE, D/E), screening stocks by criteria, symbol search
- fund_agent: mutual fund NAV, Sharpe/Sortino/Alpha/Beta/Max Drawdown, CAGR,
  side-by-side fund comparisons, AMFI scheme codes
- portfolio_agent: user's portfolio holdings and P&L, market indices
  (Nifty 50, Bank Nifty, sector performance)

Routing rules:
1. If the last message is from the user -> pick the most relevant agent
2. If the last message is from a specialist agent with a complete answer -> return FINISH
3. Never route to the same agent twice consecutively
"""

WORKER_SYSTEM = """\
You are Nivesh Agent, a personal financial research assistant for Indian equity \
markets (NSE/BSE).

Rules:
- Always call a tool to fetch live data before making specific numerical claims
- Use Rs. for Indian currency amounts
- Reference stocks by NSE symbol (e.g. RELIANCE, TCS, INFY)
- If a response contains _offline: true, note that data is from cache
- Be concise — users see a trading/research interface, not a blog post
- For fund comparisons, highlight the ranking and top recommendation
"""


# ── Graph builder ──────────────────────────────────────────────────────────────

def build_graph(memory_context: str = ""):
    """
    Build and compile the full supervisor + worker LangGraph.

    Args:
        memory_context: Optional string of known user facts from agent_memory table.
                        Injected into worker system prompts for personalisation.

    Returns:
        A compiled LangGraph StateGraph ready for ainvoke().
    """
    llm = ChatGroq(
        api_key=settings.GROQ_API_KEY,
        model=settings.AGENT_MODEL,
        temperature=0,
        max_tokens=2048,
    )

    # Worker system prompt — base + optional memory context
    worker_system = WORKER_SYSTEM
    if memory_context:
        worker_system = f"{WORKER_SYSTEM}\n\nKnown facts about the user:\n{memory_context}"

    # Build the three specialist agents
    stock_agent = build_stock_agent(llm, worker_system)
    fund_agent = build_fund_agent(llm, worker_system)
    portfolio_agent = build_portfolio_agent(llm, worker_system)

    # Supervisor LLM uses structured output for routing decisions
    router_llm = llm.with_structured_output(RouteDecision)

    # ── Node definitions ───────────────────────────────────────────────────────

    async def supervisor_node(state: AgentState) -> dict:
        """Route to a specialist agent or decide FINISH."""
        messages = [SystemMessage(content=SUPERVISOR_SYSTEM)] + list(state["messages"])
        decision = await router_llm.ainvoke(messages)
        logger.info(
            "Supervisor -> %s (reason: %s)", decision.next, decision.reason
        )
        return {"next": decision.next}

    async def run_stock_agent(state: AgentState) -> dict:
        """Invoke the stock specialist and return only the new messages it generated."""
        n_before = len(state["messages"])
        result = await stock_agent.ainvoke({"messages": list(state["messages"])})
        return {"messages": result["messages"][n_before:]}

    async def run_fund_agent(state: AgentState) -> dict:
        """Invoke the fund specialist and return only the new messages it generated."""
        n_before = len(state["messages"])
        result = await fund_agent.ainvoke({"messages": list(state["messages"])})
        return {"messages": result["messages"][n_before:]}

    async def run_portfolio_agent(state: AgentState) -> dict:
        """Invoke the portfolio/market specialist and return only the new messages it generated."""
        n_before = len(state["messages"])
        result = await portfolio_agent.ainvoke({"messages": list(state["messages"])})
        return {"messages": result["messages"][n_before:]}

    def route_next(state: AgentState) -> str:
        """Conditional edge: read state['next'] set by supervisor_node."""
        next_val = state.get("next") or ""
        if next_val == "FINISH" or not next_val:
            return END
        return next_val

    # ── Graph assembly ─────────────────────────────────────────────────────────

    graph = StateGraph(AgentState)

    graph.add_node("supervisor", supervisor_node)
    graph.add_node("stock_agent", run_stock_agent)
    graph.add_node("fund_agent", run_fund_agent)
    graph.add_node("portfolio_agent", run_portfolio_agent)

    graph.add_edge(START, "supervisor")
    graph.add_conditional_edges(
        "supervisor",
        route_next,
        {
            "stock_agent": "stock_agent",
            "fund_agent": "fund_agent",
            "portfolio_agent": "portfolio_agent",
            END: END,
        },
    )
    graph.add_edge("stock_agent", "supervisor")
    graph.add_edge("fund_agent", "supervisor")
    graph.add_edge("portfolio_agent", "supervisor")

    return graph.compile()
