"""add summary to stocks

Revision ID: fdfc78abab15
Revises: b59293c1bdc7
Create Date: 2026-04-20 16:06:12.520402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdfc78abab15'
down_revision: Union[str, Sequence[str], None] = 'b59293c1bdc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Idempotency guard for column existence
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    columns = [c['name'] for c in inspector.get_columns('stocks')]
    if 'summary' in columns:
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('summary', sa.String(length=5000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('stocks', 'summary')
